fixtures:
  repositories:
    openssl: "https://github.com/camptocamp/puppet-openssl"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"
    dism: "https://github.com/jimmybergman/puppetlabs-dism.git" 
  symlinks:
    atomia: "#{source_dir}"

