---
sudo: required
services:
  - docker
cache: bundler
language: ruby
before_install: rm Gemfile.lock || true
script: 
  - bundle exec rake
#  - ./spec/acceptance/run_acceptance_tests.sh $TEST_SUITE
matrix:
  include:
  - rvm: default
    services: docker
    env: TEST_SUITE=default
  - rvm: default
    services: docker
    env: TEST_SUITE=ubuntu-12-04
