---
sudo: required
services:
  - docker
cache: bundler
language: ruby
before_install: rm Gemfile.lock || true
script: 
  - bundle exec rake
  - bundle exec rspec spec/acceptance
matrix:
  include:
  - rvm: default
    env: BEAKER_set="default"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 2.7.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 2.7.0"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
