---
sudo: required
services:
  - docker
cache: bundler
language: ruby
before_install: rm Gemfile.lock || true
script: 
  - bundle exec rake
  - bundle exec rake spec
  - bundle exec rspec spec/acceptance/*.pp
matrix:
  include:
  - rvm: default
    services: docker
    env: BEAKER_set="ubuntu-14.04-amd64"
