---
sudo: false
cache: bundler
language: ruby
before_install: rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.1.0
script: bundle exec rake
env:
  - PUPPET_GEM_VERSION="~> 2.7.0"
  - PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
